<?php

//////////////////////////////////////////////////////////////
//===========================================================
// iscripts.php
//===========================================================
// SOFTACULOUS 
// Version : 1.1
// Inspired by the DESIRE to be the BEST OF ALL
// ----------------------------------------------------------
// Started by: Alons
// Date:       10th Jan 2009
// Time:       21:00 hrs
// Site:       http://www.softaculous.com/ (SOFTACULOUS)
// ----------------------------------------------------------
// Please Read the Terms of use at http://www.softaculous.com
// ----------------------------------------------------------
//===========================================================
// (c)Softaculous Inc.
//===========================================================
//////////////////////////////////////////////////////////////

if(!defined('SOFTACULOUS')){

	die('Hacking Attempt');

}

$iscripts = array(72 => array('name' => 'PrestaShop',
							'softname' => 'presta',
							'desc' => 'PrestaShop is professional e-Commerce shopping cart software',
							'ins' => 1,
							'cat' => 'ecommerce',
							'type' => 'php',
							'ver' => '1.6.1.24'
							),
				79 => array('name' => 'SMF',
							'softname' => 'smf',
							'desc' => 'SMF is a free, professional grade software package that allows you to set up your own online community',
							'ins' => 1,
							'cat' => 'forums',
							'type' => 'php',
							'ver' => '2.0.15'
							),
				24 => array('name' => 'Geeklog',
							'softname' => 'geeklog',
							'desc' => 'Geeklog is a PHP/MySQL based application for managing dynamic web content.',
							'ins' => 1,
							'cat' => 'cms',
							'type' => 'php',
							'ver' => '2.2.0'
							),
				13 => array('name' => 'Gallery',
							'softname' => 'gallery',
							'desc' => 'Gallery is an open source web based photo album organizer',
							'ins' => 1,
							'cat' => 'galleries',
							'type' => 'php',
							'ver' => '3.0.9'
							),
				11 => array('name' => 'Pubvana',
							'softname' => 'openb',
							'desc' => 'Kick-ass Blog application built using the CodeIgniter PHP Framework',
							'ins' => 1,
							'cat' => 'blogs',
							'type' => 'php',
							'ver' => '1.0.4'
							),
				39 => array('name' => 'Piwigo',
							'softname' => 'piwigo',
							'desc' => 'Piwigo is a photo gallery software for the web',
							'ins' => 1,
							'cat' => 'galleries',
							'type' => 'php',
							'ver' => '2.10.1'
							),
				8 => array('name' => 'AEF',
							'softname' => 'aef',
							'desc' => 'AEF - Advanced Electron Forum is a free bulletin board software written in PHP and MySQL with loads of features',
							'ins' => 1,
							'cat' => 'forums',
							'type' => 'php',
							'ver' => '1.0.9'
							),
				83 => array('name' => 'osTicket',
							'softname' => 'ostic',
							'desc' => 'osTicket is a widely-used open source support ticket system',
							'ins' => 1,
							'cat' => 'customersupport',
							'type' => 'php',
							'ver' => '1.14.1'
							),
				657 => array('name' => 'osTicket 1.12',
							'softname' => 'ostic2',
							'desc' => 'osTicket is a widely-used open source support ticket system',
							'ins' => 1,
							'cat' => 'customersupport',
							'type' => 'php',
							'ver' => '1.12.5'
							),
				55 => array('name' => 'phpList',
							'softname' => 'phplist',
							'desc' => 'phplist is an open-source newsletter manager',
							'ins' => 1,
							'cat' => 'mail',
							'type' => 'php',
							'ver' => '3.4.9'
							),
				1 => array('name' => 'Zikula',
							'softname' => 'zikula',
							'desc' => 'Zikula is a Web Application Toolkit, which allows you to run impressive websites and build powerful online applications.',
							'ins' => 1,
							'cat' => 'cms',
							'type' => 'php',
							'ver' => '2.0.15'
							),
				100 => array('name' => 'kPlaylist',
							'softname' => 'kplay',
							'desc' => 'kPlaylist is a free PHP system that makes your music collection available via the Internet',
							'ins' => 1,
							'cat' => 'music',
							'type' => 'php',
							'ver' => '1.8.502'
							),
				82 => array('name' => 'HESK',
							'softname' => 'hesk',
							'desc' => 'Hesk is Free PHP Help Desk Software that runs with a MySQL database',
							'ins' => 1,
							'cat' => 'customersupport',
							'type' => 'php',
							'ver' => '2.8.4'
							),
				86 => array('name' => 'Mibew Messenger',
							'softname' => 'owm',
							'desc' => 'Mibew Messenger is an open-source live support application written in PHP and MySQL',
							'ins' => 1,
							'cat' => 'customersupport',
							'type' => 'php',
							'ver' => '3.2.5'
							),
				57 => array('name' => 'poMMo',
							'softname' => 'pommo',
							'desc' => 'poMMo is versatile mass mailing software',
							'ins' => 1,
							'cat' => 'mail',
							'type' => 'php',
							'ver' => '16.1'
							),
				45 => array('name' => 'Revive Adserver',
							'softname' => 'openx',
							'desc' => 'Revive Adserver is a Free Open Source Ad Server formerly known as OpenX Source.',
							'ins' => 1,
							'cat' => 'admanager',
							'type' => 'php',
							'ver' => '5.0.2'
							),
				3 => array('name' => 'Serendipity',
							'softname' => 's9y',
							'desc' => 'PHP-powered, flexible Blogging/CMS application',
							'ins' => 1,
							'cat' => 'blogs',
							'type' => 'php',
							'ver' => '2.3.2'
							),
				34 => array('name' => 'Dotclear',
							'softname' => 'dotcl',
							'desc' => 'Dotclear is an open-source web publishing software',
							'ins' => 1,
							'cat' => 'blogs',
							'type' => 'php',
							'ver' => '2.15.3'
							),
				20 => array('name' => 'DokuWiki',
							'softname' => 'doku',
							'desc' => 'DokuWiki is a standards compliant, simple to use Wiki, mainly aimed at creating documentation of any kind.',
							'ins' => 1,
							'cat' => 'wikis',
							'type' => 'php',
							'ver' => '2018-04-22b'
							),
				19 => array('name' => 'WebCalendar',
							'softname' => 'webcal',
							'desc' => 'WebCalendar is a PHP-based calendar application',
							'ins' => 1,
							'cat' => 'calendars',
							'type' => 'php',
							'ver' => '1.3.0'
							),
				58 => array('name' => 'SquirrelMail',
							'softname' => 'squirrel',
							'desc' => 'SquirrelMail is a standards-based webmail package written in PHP',
							'ins' => 1,
							'cat' => 'mail',
							'type' => 'php',
							'ver' => '1.4.22'
							),
				101 => array('name' => 'Podcast Generator',
							'softname' => 'podcast',
							'desc' => 'Podcast Generator is a free web based podcast publishing script',
							'ins' => 1,
							'cat' => 'music',
							'type' => 'php',
							'ver' => '2.7'
							),
				104 => array('name' => 'BlackNova Traders',
							'softname' => 'bnt',
							'desc' => 'BlackNova Traders is a web-based, multi-player space exploration game inspired by the popular BBS game of TradeWars',
							'ins' => 1,
							'cat' => 'games',
							'type' => 'php',
							'ver' => '0.663'
							),
				38 => array('name' => 'PunBB',
							'softname' => 'punbb',
							'desc' => 'PunBB is a fast and lightweight PHP-powered discussion board.',
							'ins' => 1,
							'cat' => 'forums',
							'type' => 'php',
							'ver' => '1.4.4'
							),
				99 => array('name' => 'WeBid',
							'softname' => 'webid',
							'desc' => 'WeBid is an open-source auction script',
							'ins' => 1,
							'cat' => 'others',
							'type' => 'php',
							'ver' => '1.2.2'
							),
				105 => array('name' => 'Shadows Rising',
							'softname' => 'sr',
							'desc' => 'Shadows Rising is a browser based RPG',
							'ins' => 1,
							'cat' => 'games',
							'type' => 'php',
							'ver' => '0.0.5b'
							),
				81 => array('name' => 'Help Center Live',
							'softname' => 'hcl',
							'desc' => 'Help Center Live is a Live Support tool written in PHP',
							'ins' => 1,
							'cat' => 'customersupport',
							'type' => 'php',
							'ver' => '2.1.7'
							),
				113 => array('name' => 'Claroline',
							'softname' => 'claro',
							'desc' => 'Claroline is an Open Source eLearning and eWorking platform',
							'ins' => 1,
							'cat' => 'educational',
							'type' => 'php',
							'ver' => '1.11.10'
							),
				114 => array('name' => 'PHPfileNavigator',
							'softname' => 'pfn',
							'desc' => 'PHPfileNavigator is state-of-the-art, open source web based application to complete manage your files and folders',
							'ins' => 1,
							'cat' => 'files',
							'type' => 'php',
							'ver' => '2.3.3'
							),
				514 => array('name' => 'Mautic',
							'softname' => 'mautic',
							'desc' => 'Mautic gives you the power to track leads, personalize your engagement, offer value to your prospects and effectively guide your customers towards conversion.',
							'ins' => 1,
							'cat' => 'others',
							'type' => 'php',
							'ver' => '2.15.1'
							),
				29 => array('name' => 'dotProject',
							'softname' => 'dotproj',
							'desc' => 'dotProject is a volunteer supported Project Management application',
							'ins' => 1,
							'cat' => 'projectman',
							'type' => 'php',
							'ver' => '2.1.9'
							),
				78 => array('name' => 'Advanced Guestbook',
							'softname' => 'agb',
							'desc' => 'Advanced Guestbook is a PHP-based guestbook script',
							'ins' => 1,
							'cat' => 'guestbooks',
							'type' => 'php',
							'ver' => '2.4.4'
							),
				87 => array('name' => 'phpOnline',
							'softname' => 'phpon',
							'desc' => 'phpOnline is a live customer support system',
							'ins' => 1,
							'cat' => 'customersupport',
							'type' => 'php',
							'ver' => '2.1.3'
							),
				107 => array('name' => 'Multiplayer Checkers',
							'softname' => 'mc',
							'desc' => 'Play checkers and chat with this AJAX-enabled script',
							'ins' => 1,
							'cat' => 'games',
							'type' => 'php',
							'ver' => '1.0.0'
							),
				56 => array('name' => 'Webinsta Maillist',
							'softname' => 'mail',
							'desc' => 'WEBinsta mailing list manager is built to provide a centralized mailing list',
							'ins' => 1,
							'cat' => 'mail',
							'type' => 'php',
							'ver' => '1.3e'
							),
				49 => array('name' => 'Booked',
							'softname' => 'phpsch',
							'desc' => 'Booked (formerly phpScheduleIt) is a simple but powerful reserve-anything scheduler.',
							'ins' => 1,
							'cat' => 'calendars',
							'type' => 'php',
							'ver' => '2.7.7'
							),
				95 => array('name' => 'phpLD',
							'softname' => 'phpld',
							'desc' => 'The most widely used directory script on the internet',
							'ins' => 1,
							'cat' => 'others',
							'type' => 'php',
							'ver' => '2.2.0'
							),
				59 => array('name' => 'ccMail',
							'softname' => 'ccmail',
							'desc' => 'CcMail is a free, open, powerful Mailing List Manager',
							'ins' => 1,
							'cat' => 'mail',
							'type' => 'php',
							'ver' => '1.0.2'
							),
				76 => array('name' => 'Lazarus',
							'softname' => 'lazarus',
							'desc' => 'Lazarus is a free guestbook script written in PHP',
							'ins' => 1,
							'cat' => 'guestbooks',
							'type' => 'php',
							'ver' => '1.24'
							),
				98 => array('name' => 'Moodle 2.6',
							'softname' => 'moodle',
							'desc' => 'Moodle is a Course Management System',
							'ins' => 1,
							'cat' => 'educational',
							'type' => 'php',
							'ver' => '2.6.11'
							),
				74 => array('name' => 'BellaBook',
							'softname' => 'bella',
							'desc' => 'BellaBook is a small and simple PHP guestbook',
							'ins' => 1,
							'cat' => 'guestbooks',
							'type' => 'php',
							'ver' => '3.7'
							),
				64 => array('name' => 'LittlePoll',
							'softname' => 'little',
							'desc' => 'The Amazing Little Poll is a very simple php polling script',
							'ins' => 1,
							'cat' => 'polls',
							'type' => 'php',
							'ver' => '1.4'
							),
				80 => array('name' => 'Sales Syntax',
							'softname' => 'crafty',
							'desc' => 'Sales Syntax Live Help (CSLH) is an open source live support solution',
							'ins' => 1,
							'cat' => 'customersupport',
							'type' => 'php',
							'ver' => '3.6.2'
							),
				61 => array('name' => 'phpESP',
							'softname' => 'phpesp',
							'desc' => 'Create surveys, administer surveys, gather results, view statistics',
							'ins' => 1,
							'cat' => 'polls',
							'type' => 'php',
							'ver' => '2.1.4'
							),
				43 => array('name' => 'PmWiki',
							'softname' => 'pmwiki',
							'desc' => 'PmWiki is a wiki-based system for collaborative creation and maintenance of websites',
							'ins' => 1,
							'cat' => 'wikis',
							'type' => 'php',
							'ver' => '2.2.122'
							),
				106 => array('name' => 'Word Search Puzzle',
							'softname' => 'wsp',
							'desc' => 'Word Search Puzzle is a fun and simple game',
							'ins' => 1,
							'cat' => 'games',
							'type' => 'php',
							'ver' => '1.0'
							),
				73 => array('name' => 'phpBook',
							'softname' => 'phpbook',
							'desc' => 'Allows you to add free guestbook to your site',
							'ins' => 1,
							'cat' => 'guestbooks',
							'type' => 'php',
							'ver' => '2.1.0'
							),
				48 => array('name' => 'phpicalendar',
							'softname' => 'phpical',
							'desc' => 'phpicalendar is an open source php application to parse and display shared icalendar-compatible calendars on a website',
							'ins' => 1,
							'cat' => 'calendars',
							'type' => 'php',
							'ver' => '2.31'
							),
				102 => array('name' => 'Impleo',
							'softname' => 'impleo',
							'desc' => 'Impleo is a simple PHP-script for managing your record collection',
							'ins' => 1,
							'cat' => 'music',
							'type' => 'php',
							'ver' => '2.0'
							),
				88 => array('name' => 'Aardvark Topsites',
							'softname' => 'ats',
							'desc' => 'Aardvark Topsites PHP is a free topsites script built on PHP and MySQL',
							'ins' => 1,
							'cat' => 'polls',
							'type' => 'php',
							'ver' => '5.2.1'
							),
				75 => array('name' => 'VX Guestbook',
							'softname' => 'vxgb',
							'desc' => 'Allows you to add free guestbook to your site',
							'ins' => 1,
							'cat' => 'guestbooks',
							'type' => 'php',
							'ver' => '1.07'
							),
				77 => array('name' => 'RicarGBooK',
							'softname' => 'ricar',
							'desc' => 'RicarGBooK is a guestbook system written in PHP',
							'ins' => 1,
							'cat' => 'guestbooks',
							'type' => 'php',
							'ver' => '1.2.2'
							),
				164 => array('name' => 'Raphael',
							'softname' => 'raphael',
							'desc' => 'Raphael is a small JavaScript library that should simplify your work with vector graphics on the web',
							'ins' => 1,
							'cat' => 'libraries',
							'type' => 'js',
							'ver' => '2.3.0'
							),
				161 => array('name' => 'Rico',
							'softname' => 'rico',
							'desc' => 'Javascript for rich internet applications',
							'ins' => 1,
							'cat' => 'libraries',
							'type' => 'js',
							'ver' => '2.1'
							)
			);

?>